### ISSUE TITLE
Error-troubleshooting, and step to run multiple sample using multiple threads

### ISSUE THREAD

**Issue by rickyalfaray** [deprekate/PHACTS#3]
Hi, 

Thank you for making this nice tool.
I tried to install it by using pip, but it was an error. 
```
FileNotFoundError: [Errno 2] No such file or directory: 'fasta35': 'fasta35'
```
I tried to copy-paste manually the file fasta35 into my bin, and run again the test, but it was an error again.

```
$ phacts.py /data/Ricky/MGE/phaster/NEW_All_Phaster_Results_Worldwide/Analysis_phage/phacts/PHACTS/tests/NC_001416.faa
Traceback (most recent call last):
  File "/data/Ricky/Software/Miniconda/envs/MGE/bin/phacts.py", line 84, in <module>
    p = Popen(['fasta35', '-b', '1','@', args.infile], stdout=PIPE, stdin=PIPE, stderr=PIPE)
  File "/data/Ricky/Software/Miniconda/envs/MGE/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data/Ricky/Software/Miniconda/envs/MGE/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'fasta35' 
```

When I tried to change the permission, this notification appeared:

```
Traceback (most recent call last):
  File "/data/Ricky/Software/Miniconda/envs/MGE/bin/phacts.py", line 84, in <module>
    p = Popen(['fasta35', '-b', '1','@', args.infile], stdout=PIPE, stdin=PIPE, stderr=PIPE)
  File "/data/Ricky/Software/Miniconda/envs/MGE/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data/Ricky/Software/Miniconda/envs/MGE/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'fasta35'
```

Could you please help?

**Comment by rickyalfaray** [comment]
When I tried to change the permission, this notification appeared:

`Traceback (most recent call last):
  File "/data/Ricky/Software/Miniconda/envs/MGE/bin/phacts.py", line 84, in <module>
    p = Popen(['fasta35', '-b', '1','@', args.infile], stdout=PIPE, stdin=PIPE, stderr=PIPE)
  File "/data/Ricky/Software/Miniconda/envs/MGE/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data/Ricky/Software/Miniconda/envs/MGE/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'fasta35'`

**Comment by deprekate** [comment]
I have changed the code so it should automatically copy over the two binaries, and then try to run the appropriate one: linux vs OSX (I will try to get around to adding a Windows one). 

What OS are you on?

**Comment by rickyalfaray** [comment]
Thank you for your reply.
I'm using Linux, and I'm new to this.

I tried to install it again in the new environment (Python 3.7.12) by pip
Again, the installation works well.

```
`(phage) [Ricky@expsrv phacts]$ pip install phacts
Collecting phacts
  Downloading phacts-1.5-py3-none-any.whl (8.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 13.3 MB/s eta 0:00:00
Collecting dill
  Using cached dill-0.3.4-py2.py3-none-any.whl (86 kB)
Collecting numpy
  Downloading numpy-1.22.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 13.7 MB/s eta 0:00:00
Collecting sklearn
  Using cached sklearn-0.0.tar.gz (1.1 kB)
  Preparing metadata (setup.py) ... done
Collecting scikit-learn
  Downloading scikit_learn-1.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.5/26.5 MB 13.1 MB/s eta 0:00:00
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Collecting joblib>=0.11
  Downloading joblib-1.1.0-py2.py3-none-any.whl (306 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 307.0/307.0 KB 23.0 MB/s eta 0:00:00
Collecting scipy>=1.1.0
  Downloading scipy-1.8.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (42.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 MB 12.2 MB/s eta 0:00:00
Building wheels for collected packages: sklearn
  Building wheel for sklearn (setup.py) ... done
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1310 sha256=b7c532fce8fb2c470a1283d4d2291e91e7f311c33100fed6bfe6f7428c42c089
  Stored in directory: /home/student/Ricky/.cache/pip/wheels/9b/13/01/6f3a7fd641f90e1f6c8c7cded057f3394f451f340371c68f3d
Successfully built sklearn
Installing collected packages: threadpoolctl, numpy, joblib, dill, scipy, scikit-learn, sklearn, phacts
Successfully installed dill-0.3.4 joblib-1.1.0 numpy-1.22.3 phacts-1.5 scikit-learn-1.0.2 scipy-1.8.0 sklearn-0.0 threadpoolctl-3.1.0
`
```
I try to check

````
(phage) [Ricky@expsrv phacts]$ phacts.py -h
usage: /data/Ricky/Software/Miniconda/envs/phage/bin/phacts.py [-opt1, [-opt2, ...]] infile

positional arguments:
  infile                input file

options:
  -h, --help            show this help message and exit
  -o OUTFILE, --outfile OUTFILE
                        where to write output [stdout]
  -c CUTOFF, --cutoff CUTOFF
                        The minimum cutoff length for runs
  -g NUM_GENOMES, --num_genomes NUM_GENOMES
  -p NUM_PROTEINS, --num_proteins NUM_PROTEINS
  -r REPLICATES, --replicates REPLICATES
````

I also tried to use the example data and it works well.

```
(phage) [Ricky@expsrv phacts]$ phacts.py NC_000866.faa
Class   probability     standard deviation
Lytic   0.8084915084915085      0.07560008953401683
```

However, when using my sequence, this notification appeared:

```
Traceback (most recent call last):
  File "/data/Ricky/Software/Miniconda/envs/phage/bin/phacts.py", line 105, in <module>
    X[0,j] = float( line.split(' ')[3].replace('%','') )
ValueError: could not convert string to float: ''
```

My data is like this (I tried with or without asterisk in the end of each seqeunce):

```
>804_Hp_H_34_00009 Glutamate--tRNA ligase 1
MSLIVTRFAPSPTGYLHIGGLRTAIFNYLFARANQGKFFLRIEDTDLSRNSIEAANAIIEAFKWVGLEHDGEILYQSKRFEIYKEYIQKLLDEDKAYYCYMSKDELDALREEQKARKETPRYDNRYRDFKGTPPKGVEPVVRIKVPQNEVIGFNDGVKGEVKVNTNGIDDFIIARSDGTPTYNFVVTIDDALMGITDVIRGDDHLSNTPKQIVLYKALNFKIPNFFHVPMILNEEGQKLSKRHGATNVMDYQEMGYLKEALVNFLARLGWSYQDKEIFSMQELLECFDPKDLNSSPSCFSWHKLNWLNAHYLKNQSAQELLKLLKPFSFSDLSHLNPAQLDRLLDALKERSQTLKELALKIDEVLIAPVEYEEKIFKKLNQALVMPLLEKFKLALDKADFNDESALEDAMHQIIEEEKIKTGSFMQPLRLALLGKGGGIGLKEALFILGKTESVKRIEAFLKS
>804_Hp_H_34_00010 hypothetical protein
MQFQKTLFPLSLFLSLFLSFGIAEENGAYASVGFEYSISHAVEHNNPFSNQERIQTISNAQNKIYKLNQVKNEITNMPNTFNYINNALKNHAKLTPTEKQAEQYYLQSTLQNIEKIMMLSGGVASNLKLAQALEKMQEPITNPLELAENLRNLELQFSQSQNNMLSSLSSQIAAISNSLNALDPSSYSKNVSSMYGVGLSVGYKHFFTKKKNQGFRYYLFYDYGYTNFGFVGNGFDGLGKMNNHLYGLGIDYLFNFIDNAKKHSSVGFYAGFALAGSSWVGSGLGMWVSQTDFINNYLTGYQAKMHTSFFQIPLNFGVRVNVDRHNGFEMGLKIPLAVNSFYETHGKGLNASLFFKRLVVFNVSYVYSF
>804_Hp_H_34_00011 hypothetical protein
MPSNALLIGEIAHLINVSHSSVRNWIKTNLLEKLEIDHKIYVKTSSFLDFCRNHLGKNKLNKYANKSLKSVHNHQELILKYLEMLENSSDLEKLGSYYEEELSNTTRNLEGIYYTPNRIVEQLFTLPKDFDASQAIFCDPAVGSGNFVMHALKLGFKVENIYGYDTGAFAVALTKKRIKERYRLDCPNIVQKDFLSLKHAPQFDCIFTNPPWGKKYNQNQKENFKQKFNLHQSLDSASLFFIASLNCLKENAHLGLLLPESCLNIDAFSKMREMALKFQMRSLIDFDKPFKNLMTKAVGLALKKTPNKDQKISCFYQNSKFKRSPSSFFNNPKKIFNIHCSNKENKILDHLFSIPHMTLENNAHFALGIVTGNNEEKLHPKQEKNTIPIFRGSDILKDGLKAPSQFINADLRDCQQVAPLSLYQAREKIVYKFISSKLVFFYDNKQRLFLNSANMFVLKENFPINAHALKELLNSDLMQFIFESLFKTHKILRKDLECLPLFAQFINNGFDEKFYLKNLGIEKKDPKHFTIRKNHAHRLSFGFRG
>804_Hp_H_34_00012 hypothetical protein
MRIACLLALGDNLITLSLLTEIALKRQQPLKILGTRLTLKIAKILECEKHFEIIPVFENVPAFYDLKKQGVFGAMKDFLRLLKALKKHKIKRLILEKQDFRSALLSQFIPITTPNKEIKNVYQNRQELFSQIYGHVFDNPPYPMNLKNPKKILINPFTRENDRNISLEHLKIVLKLLKPFCVTLLDFEERYAFLKDEVTHYRAKTSLEEVKNLILESDLYIGGDSFLIHLAYYLKKNYFIFFYRDNDDFMPPNSGNENFLEAHKSHLIEQDLAKKFRHLGLL
```

Same format with the example file of NC_000866.faa

```
>NC_000866_orf_[11:2189](-) rIIA protector from prophage-induced early lysis
MIITTEKETILGNGSKSKAFSITASPKVFKILSSDLYTNKIRAVVRELITNMIDAHALNGNPEKFIIQVPGRLDPRFVCRDFGPGMSDFDIQGDDNSPGLYNSYFSSSKAESNDFIGGFGLGSKSPFSYTDTFSITSYHKGEIRGYVAYMDGDGPQIKPTFVKEMGPDDKTGIEIVVPVEEKDFRNFAYEVSYIMRPFKDLAIINGLDREIDYFPDFDDYYGVNPERYWPDRGGLYAIYGGIVYPIDGVIRDRNWLSIRNEVNYIKFPMGSLDIAPSREALSLDDRTRKNIIERVKELSEKAFNEDVKRFKESTSPRHTYRELMKMGYSARDYMISNSVKFTTKNLSYKKMQSMFEPDSKLCNAGVVYEVNLDPRLKRIKQSHETSAVASSYRLFGINTTKINIVIDNIKNRVNIVRGLARALDDSEFNNTLNIHHNERLLFINPEVESQIDLLPDIMAMFESDEVNIHYLSEIEALVKSYIPKVVKSKAPRPKAATAFKFEIKDGRWEKRNYLRLTSEADEITGYVAYMHRSDIFSMDGTTSLCHPSMNILIRMANLIGINEFYVIRPLLQKKVKELGQCQCIFEALRDLYVDAFDDVDYDKYVGYSSSAKRYIDKIIKYPELDFMMKYFSIDEVSEEYTRLANMVSSLQGVYFNGGKDTIGHDIWTVTNLFDVLSNNASKNSDKMVAEFTKKFRIVSDFIGYRNSLSDDEVSQIAKTMKALAA*
>NC_000866_orf_[2199:2403](-) rIIA.1 hypothetical protein
MKSYKVNLELFDKAVHREYRIIQRFFDMGEAEEFKTRFKDIRDKIQSDTATKDELLEVAEVIKRNMN*
>NC_000866_orf_join{[2852:2990](-), [2457:2802](-)} gp60 topoisomerase II, large subunit, C-terminal region
MKFVKIDSSSVDMKKYKLQNNVRRSIKSSSMNYANVAIMTDADHDGLGSIYPSLLGFFSNWPELFEQGRIRFVKTPVIIAQVGKKQEWFYTVAEYESAKDALPKHSIRYIKGLGSLEKSEYREMIQNPVYDVVKLPENWKELFEMLMGDNADLRKEWMSQ*
>NC_000866_orf_[2970:3351](-) gp60.1 hypothetical protein
MTCFKNEKGEVFRLHVNDPRIKTEKLVGVGNTVAATAKAAELEKAKPWYNKSATNPEAVKLIPNLYEWYVTKYDPDHYKRTGVAKWKSVNNITVNSKLFGRAFNEFKRGWIPDEKFYEVYNEICKN*
```

Actually, the original .faa from prokka is not one line. 
Thus, I tried to change the format into one line by using seqkit tool, so the sequence will be one line like above. 

Could you please give me some suggestions?

Thank you.

**Comment by rickyalfaray** [comment]
I also tried to use the example data and it works well.
However, using my sequence the notification appeared:

```
Traceback (most recent call last):
  File "/data/Ricky/Software/Miniconda/envs/phage/bin/phacts.py", line 105, in <module>
    X[0,j] = float( line.split(' ')[3].replace('%','') )
ValueError: could not convert string to float: ''
```

My data is like this:

```
>804_Hp_H_34_00009 Glutamate--tRNA ligase 1
MSLIVTRFAPSPTGYLHIGGLRTAIFNYLFARANQGKFFLRIEDTDLSRNSIEAANAIIEAFKWVGLEHDGEILYQSKRFEIYKEYIQKLLDEDKAYYCYMSKDELDALREEQKARKETPRYDNRYRDFKGTPPKGVEPVVRIKVPQNEVIGFNDGVKGEVKVNTNGIDDFIIARSDGTPTYNFVVTIDDALMGITDVIRGDDHLSNTPKQIVLYKALNFKIPNFFHVPMILNEEGQKLSKRHGATNVMDYQEMGYLKEALVNFLARLGWSYQDKEIFSMQELLECFDPKDLNSSPSCFSWHKLNWLNAHYLKNQSAQELLKLLKPFSFSDLSHLNPAQLDRLLDALKERSQTLKELALKIDEVLIAPVEYEEKIFKKLNQALVMPLLEKFKLALDKADFNDESALEDAMHQIIEEEKIKTGSFMQPLRLALLGKGGGIGLKEALFILGKTESVKRIEAFLKS
>804_Hp_H_34_00010 hypothetical protein
MQFQKTLFPLSLFLSLFLSFGIAEENGAYASVGFEYSISHAVEHNNPFSNQERIQTISNAQNKIYKLNQVKNEITNMPNTFNYINNALKNHAKLTPTEKQAEQYYLQSTLQNIEKIMMLSGGVASNLKLAQALEKMQEPITNPLELAENLRNLELQFSQSQNNMLSSLSSQIAAISNSLNALDPSSYSKNVSSMYGVGLSVGYKHFFTKKKNQGFRYYLFYDYGYTNFGFVGNGFDGLGKMNNHLYGLGIDYLFNFIDNAKKHSSVGFYAGFALAGSSWVGSGLGMWVSQTDFINNYLTGYQAKMHTSFFQIPLNFGVRVNVDRHNGFEMGLKIPLAVNSFYETHGKGLNASLFFKRLVVFNVSYVYSF
>804_Hp_H_34_00011 hypothetical protein
MPSNALLIGEIAHLINVSHSSVRNWIKTNLLEKLEIDHKIYVKTSSFLDFCRNHLGKNKLNKYANKSLKSVHNHQELILKYLEMLENSSDLEKLGSYYEEELSNTTRNLEGIYYTPNRIVEQLFTLPKDFDASQAIFCDPAVGSGNFVMHALKLGFKVENIYGYDTGAFAVALTKKRIKERYRLDCPNIVQKDFLSLKHAPQFDCIFTNPPWGKKYNQNQKENFKQKFNLHQSLDSASLFFIASLNCLKENAHLGLLLPESCLNIDAFSKMREMALKFQMRSLIDFDKPFKNLMTKAVGLALKKTPNKDQKISCFYQNSKFKRSPSSFFNNPKKIFNIHCSNKENKILDHLFSIPHMTLENNAHFALGIVTGNNEEKLHPKQEKNTIPIFRGSDILKDGLKAPSQFINADLRDCQQVAPLSLYQAREKIVYKFISSKLVFFYDNKQRLFLNSANMFVLKENFPINAHALKELLNSDLMQFIFESLFKTHKILRKDLECLPLFAQFINNGFDEKFYLKNLGIEKKDPKHFTIRKNHAHRLSFGFRG
>804_Hp_H_34_00012 hypothetical protein
MRIACLLALGDNLITLSLLTEIALKRQQPLKILGTRLTLKIAKILECEKHFEIIPVFENVPAFYDLKKQGVFGAMKDFLRLLKALKKHKIKRLILEKQDFRSALLSQFIPITTPNKEIKNVYQNRQELFSQIYGHVFDNPPYPMNLKNPKKILINPFTRENDRNISLEHLKIVLKLLKPFCVTLLDFEERYAFLKDEVTHYRAKTSLEEVKNLILESDLYIGGDSFLIHLAYYLKKNYFIFFYRDNDDFMPPNSGNENFLEAHKSHLIEQDLAKKFRHLGLL
```

Same format with the example file of NC_000866.faa

```
>NC_000866_orf_[11:2189](-) rIIA protector from prophage-induced early lysis
MIITTEKETILGNGSKSKAFSITASPKVFKILSSDLYTNKIRAVVRELITNMIDAHALNGNPEKFIIQVPGRLDPRFVCRDFGPGMSDFDIQGDDNSPGLYNSYFSSSKAESNDFIGGFGLGSKSPFSYTDTFSITSYHKGEIRGYVAYMDGDGPQIKPTFVKEMGPDDKTGIEIVVPVEEKDFRNFAYEVSYIMRPFKDLAIINGLDREIDYFPDFDDYYGVNPERYWPDRGGLYAIYGGIVYPIDGVIRDRNWLSIRNEVNYIKFPMGSLDIAPSREALSLDDRTRKNIIERVKELSEKAFNEDVKRFKESTSPRHTYRELMKMGYSARDYMISNSVKFTTKNLSYKKMQSMFEPDSKLCNAGVVYEVNLDPRLKRIKQSHETSAVASSYRLFGINTTKINIVIDNIKNRVNIVRGLARALDDSEFNNTLNIHHNERLLFINPEVESQIDLLPDIMAMFESDEVNIHYLSEIEALVKSYIPKVVKSKAPRPKAATAFKFEIKDGRWEKRNYLRLTSEADEITGYVAYMHRSDIFSMDGTTSLCHPSMNILIRMANLIGINEFYVIRPLLQKKVKELGQCQCIFEALRDLYVDAFDDVDYDKYVGYSSSAKRYIDKIIKYPELDFMMKYFSIDEVSEEYTRLANMVSSLQGVYFNGGKDTIGHDIWTVTNLFDVLSNNASKNSDKMVAEFTKKFRIVSDFIGYRNSLSDDEVSQIAKTMKALAA*
>NC_000866_orf_[2199:2403](-) rIIA.1 hypothetical protein
MKSYKVNLELFDKAVHREYRIIQRFFDMGEAEEFKTRFKDIRDKIQSDTATKDELLEVAEVIKRNMN*
>NC_000866_orf_join{[2852:2990](-), [2457:2802](-)} gp60 topoisomerase II, large subunit, C-terminal region
MKFVKIDSSSVDMKKYKLQNNVRRSIKSSSMNYANVAIMTDADHDGLGSIYPSLLGFFSNWPELFEQGRIRFVKTPVIIAQVGKKQEWFYTVAEYESAKDALPKHSIRYIKGLGSLEKSEYREMIQNPVYDVVKLPENWKELFEMLMGDNADLRKEWMSQ*
>NC_000866_orf_[2970:3351](-) gp60.1 hypothetical protein
MTCFKNEKGEVFRLHVNDPRIKTEKLVGVGNTVAATAKAAELEKAKPWYNKSATNPEAVKLIPNLYEWYVTKYDPDHYKRTGVAKWKSVNNITVNSKLFGRAFNEFKRGWIPDEKFYEVYNEICKN*
```

Actually the original .faa from prokka is not one line. Thus, I tried to change the format into one line by using seqkit tool, so seqeunce will be one line like above. 

May I know which step I should change? Could you please give me some suggestions?

Thank you.

**Comment by deprekate** [comment]
Hm, it looks like there is something different about the output from the fasta35 command.  It is finding the line that starts with "Smith-Waterman" then splitting on the space character, but the expected position of the % identity is empty, hence the ''

I have added an error trap to the code, so that when it runs into the error, it dumps the entire contents of the fasta35 output to stdin

If you could run the newest version 1.5.1 on pip, and send me the output, it would be invaluable in tracking down the source of the bug.
```
$ phacts.py infile.faa > output.txt
```



The output of fasta35 looks like (i just ran one of the NC_000866 proteins against itself):
```
# ./phacts/linux.fasta35 -b 1 one.faa one.faa
FASTA searches a protein or DNA sequence data bank
 version 35.01 May 30, 2007
Query: one.faa
  1>>>NC_000866_orf_[2199:2403](-) rIIA.1 hypothetic 67 aa - 67 aa
Library: one.faa      67 residues in     1 sequences
     67 residues in     1 sequences
Statistics: (shuffled [500]) MLE statistics: Lambda= 0.1281;  K=0.008426
Algorithm: FASTA (3.5 Sept 2006) [optimized]
Parameters: BL50 matrix (15:-5) ktup: 2
 join: 36, opt: 24, open/ext: -10/-2, width:  16

The best scores are:                                      opt bits E(1)
NC_000866_orf_[2199:2403](-) rIIA.1 hypothetical p (  67)  426 85.6 7.5e-23
>>NC_000866_orf_[2199:2403](-) rIIA.1 hypothetical prote  (67 aa)
 initn: 426 init1: 426 opt: 426  Z-score: 442.7  bits: 85.6 E(): 7.5e-23

Smith-Waterman score: 426; 100.0% identity (100.0% similar) in 67 aa overlap (1-67:1-67)
               10        20        30        40        50        60
NC_000 MKSYKVNLELFDKAVHREYRIIQRFFDMGEAEEFKTRFKDIRDKIQSDTATKDELLEVAE
       ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
NC_000 MKSYKVNLELFDKAVHREYRIIQRFFDMGEAEEFKTRFKDIRDKIQSDTATKDELLEVAE
               10        20        30        40        50        60             
NC_000 VIKRNMN
       :::::::
NC_000 VIKRNMN

**Comment by rickyalfaray** [comment]
Thank you. It works!
I already tried to install the new one

```
(phage_new) [Ricky@expsrv phacts]$ pip install phacts==1.5.1
```

Then I tried to run using the example file and my file, then it works. 
Thank you!

When I tried to run using the example file, the results is like this:
 
```
(phage_new) [Ricky@expsrv phacts]$ phacts.py NC_000866.faa > output_example.txt
(phage_new) [Ricky@expsrv phacts]$ cat output_example.txt
Class   probability     standard deviation
Lytic   0.8125874125874126      0.0674768789178473
```

When I tried to run using my sample (original from Prokka results, without any line modification), it gave the results, 
however, I couldn't find the probability.
```
(phage_new) [Ricky@expsrv phacts]$ phacts.py phage_804_Hp_H_34.faa > output_myfile.txt
```
About sharing the output results, sure, I'm happy to help and share.
The results and the file that I used can be accessed from here:

[learning_phacts](https://drive.google.com/drive/folders/1r2IINDKJfZNIGMPD7wBj4P7kA9W_LIid?usp=sharing)

May I know where is the probability of the lytic phase?
Is it possible to run for hundreds of sequences by using commands other than using [this step](https://github.com/deprekate/PHACTS/issues/1#issuecomment-913839208)? Maybe by looping?
Also, can we specify the threads that we want to use?
Thank you.

**Comment by deprekate** [comment]
Awesome, I tracked down the bug.  It turns out it was caused when I parsed the line:
```
Smith-Waterman score: 39;  9.8% identity (68.3% similar) in 41 aa overlap (2-42:36-76)
```
When I split on the space character in python I used `line.split(' ')` instead of `line.split()`, the former treats each space as a distinct separator, while the later treats consecutive spaces as one space.  The bad line had such a low percent identity (9.8%), that fasta35 padded it with two spaces.  I fixed the code and pushed it to pip, so it should be working fine now.  Thanks for you help tracking the bug down.

fyi, it looks like your 804 phage is probably temperate.  This is the output from running it through phacts (using 50 replicates instead of the default 10, which takes a little longer, but allows the prediction to converge on the true value).
```
$ phacts.py PHACTS/phage_804_Hp_H_34.faa -r 50
Class	probability	standard deviation
Temperate	0.5282517482517483	0.04258477264017631
```

**Comment by deprekate** [comment]
As far as running phacts on hundreds of phages.
Normally I run my big jobs on clusters that have hundreds of cores.

However you should be able to do the same on a regular computer.  The easiest would be to use the linux command `xargs`.  The syntax to run on the two test genomes with one command would be (you will need to update to a newer phacts version since I wasn't writing to the `-o` argument correctly):
```
$ pip install phacts==1.7
$ ls tests/ | xargs -I{} phacts.py tests/{} -o {}.txt
```
*be careful with the above command, I don't have phacts checking to make sure the file given to the `-o` does not exist (yet), so it will overwrite any existing file with the same name


The old version of phacts had threading implementation, but not the new one (yet).  So when you run a single phacts job, it runs 10 replicates serially instead of parallel, which is why if you bump the `-r` up to 50, it takes 5 times as long.
When you run the above `xargs` command it will run each job serially, one after the other.  It takes about 3 minutes to run the two test genomes through phacts on my laptop.  So you could potentially get a few hundred genomes through using that command, in about a day.

If you have thousands of genomes (or want to bump up the `-r` replicates),  instead of `xargs` you can use the `parallel` [command](https://opensource.com/article/18/5/gnu-parallel), which will use multiple cores, so if you have 8 cores, 8 jobs will run at once.  When a job finishes, a new job will be sent to that core to run.  This will allow you to get thousands of genomes through, in a reasonable amount of time.  
The syntax for `parallel` is very similiar to `xargs`:
```
$ ls tests/ | parallel -I{} phacts.py tests/{} -o {}.txt
```

**Comment by rickyalfaray** [comment]
Great!
I already tried. It works very well with phacts==1.7.
I also tried to use the parallel command as you suggested, and it works.
Now I got all the results. 
Thank you so much! ( ^◡^)👍

**Comment by rickyalfaray** [comment]
Great!
I already tried. It works very well with phacts==1.7.
I also tried to use the parallel command as you suggested, and it works.
Now I got all the results.
Thank you so much! ( ^◡^)👍

**Comment by serzero2007** [comment]
> Awesome, I tracked down the bug. It turns out it was caused when I parsed the line:
> 
> ```
> Smith-Waterman score: 39;  9.8% identity (68.3% similar) in 41 aa overlap (2-42:36-76)
> ```
> 
> When I split on the space character in python I used `line.split(' ')` instead of `line.split()`, the former treats each space as a distinct separator, while the later treats consecutive spaces as one space. The bad line had such a low percent identity (9.8%), that fasta35 padded it with two spaces. I fixed the code and pushed it to pip, so it should be working fine now. Thanks for you help tracking the bug down.
> 
> fyi, it looks like your 804 phage is probably temperate. This is the output from running it through phacts (using 50 replicates instead of the default 10, which takes a little longer, but allows the prediction to converge on the true value).
> 
> ```
> $ phacts.py PHACTS/phage_804_Hp_H_34.faa -r 50
> Class	probability	standard deviation
> Temperate	0.5282517482517483	0.04258477264017631
> ```

When probability is 0.5, that means that Phacts can call it neither lytic, nor temperate. Look at standard deviation: when you run phacts once again, it may end up with lytic as a result.
